# Generated by Django 5.0.3 on 2024-06-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Order Id')),
                ('order_date', models.DateTimeField(verbose_name='Order Date')),
                ('billing_address', models.TextField(default='', max_length=1000, verbose_name='Billing Address')),
                ('shipping_address', models.TextField(default='', max_length=1000, verbose_name='Shipping Address')),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('failed to delivered', 'Failed To Delivered'), ('out for delivery', 'Out for delivery'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('refund requested', 'Refund Requested')], max_length=50, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Order Created at')),
            ],
            options={
                'verbose_name': 'SellerOrder',
                'verbose_name_plural': 'SellerOrders',
            },
        ),
    ]
