# Generated by Django 4.1.3 on 2023-02-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelTable(
            name='blogs',
            table='Blogs',
        ),
    ]
