# Generated by Django 4.1.3 on 2023-02-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_options_alter_blogs_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='slug',
        ),
    ]
