# Generated by Django 4.1.3 on 2023-02-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image1',
            field=models.ImageField(blank=True, height_field='image1_height', null=True, upload_to='blogs/media/BlogImages/%Y/%m/%d', verbose_name='Blog Image 1', width_field='image2_width'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/media/BlogImages/%Y/%m/%d', verbose_name='Blog Image 2'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/media/BlogImages/%Y/%m/%d', verbose_name='Blog Image 3'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='imageMain',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/media/BlogBgImages/%Y/%m/%d', verbose_name='Blog Title Background Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='mainpage_image',
            field=models.ImageField(blank=True, height_field='mainpage_height', null=True, upload_to='blogs/media/mainPageImage/%Y/%m/%d', verbose_name='Main Page Image', width_field='mainpage_width'),
        ),
    ]
