# Generated by Django 4.1.3 on 2023-02-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_image1_alter_blogs_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image1',
            field=models.ImageField(blank=True, height_field='image1_height', null=True, upload_to='blogs/media/BlogImages/%Y/%m/%d', verbose_name='Blog Image 1', width_field='image1_width'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='mainpage_image',
            field=models.ImageField(blank=True, height_field='mainpage_image_height', null=True, upload_to='blogs/media/mainPageImage/%Y/%m/%d', verbose_name='Main Page Image', width_field='mainpage_image_width'),
        ),
    ]
