# Generated by Django 4.1.3 on 2023-02-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_image1_alter_blogs_mainpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/media/BlogImages/%Y/%m/%d', verbose_name='Blog Image 1'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='mainpage_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/media/mainPageImage/%Y/%m/%d', verbose_name='Main Page Image'),
        ),
    ]
