# Generated by Django 4.1.3 on 2024-04-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middlewares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatalog',
            name='mobile',
            field=models.BooleanField(default=False),
        ),
    ]
