# Generated by Django 4.1.3 on 2024-04-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middlewares', '0002_requestdatalog_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatalog',
            name='is_new_user',
            field=models.BooleanField(default=False),
        ),
    ]
