# Generated by Django 4.1.3 on 2024-04-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middlewares', '0003_requestdatalog_is_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdatalog',
            name='client_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestdatalog',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
