# Generated by Django 4.1.3 on 2024-02-18 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_alter_delaydeliveryandrefundemails_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delaydeliveryandrefundemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 18, 23, 35, 34, 269058), null=True),
        ),
        migrations.AlterField(
            model_name='paymentsemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 18, 23, 35, 34, 268626), null=True),
        ),
        migrations.AlterField(
            model_name='promotionalemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 18, 23, 35, 34, 268933), null=True),
        ),
        migrations.AlterField(
            model_name='userregisteredemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 18, 23, 35, 34, 268761), null=True),
        ),
    ]
