# Generated by Django 4.1.3 on 2024-02-21 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_alter_delaydeliveryandrefundemails_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delaydeliveryandrefundemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 21, 12, 5, 9, 93163), null=True),
        ),
        migrations.AlterField(
            model_name='paymentsemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 21, 12, 5, 9, 92711), null=True),
        ),
        migrations.AlterField(
            model_name='promotionalemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 21, 12, 5, 9, 93030), null=True),
        ),
        migrations.AlterField(
            model_name='userregisteredemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 21, 12, 5, 9, 92854), null=True),
        ),
    ]
