# Generated by Django 4.1.3 on 2024-04-24 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0005_alter_delaydeliveryandrefundemails_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delaydeliveryandrefundemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 12, 39, 38, 961129), null=True),
        ),
        migrations.AlterField(
            model_name='paymentsemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 12, 39, 38, 960678), null=True),
        ),
        migrations.AlterField(
            model_name='promotionalemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 12, 39, 38, 961005), null=True),
        ),
        migrations.AlterField(
            model_name='userregisteredemails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 24, 12, 39, 38, 960828), null=True),
        ),
    ]
