# Generated by Django 4.1.3 on 2024-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrder',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Order Id')),
                ('order_date', models.DateTimeField(verbose_name='Order Date')),
                ('customer_info', models.TextField(verbose_name='Customer Info')),
                ('items', models.CharField(blank=True, max_length=500, null=True, verbose_name='Items')),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('failed to delivered', 'Failed To Delivered'), ('out for delivery', 'Out for delivery'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('refund requested', 'Refund Requested')], max_length=50, verbose_name='Order Status')),
            ],
            options={
                'verbose_name': 'SellerOrder',
                'verbose_name_plural': 'SellerOrders',
            },
        ),
    ]
