# Generated by Django 4.0.4 on 2023-08-24 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(blank=True, default='L', max_length=50, null=True, verbose_name='Item Size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Courier Partner Name')),
                ('address', models.CharField(max_length=2000, verbose_name='Courier Partner Address')),
                ('contact_no', models.CharField(max_length=50, verbose_name='Courier Partner Contact No')),
                ('customer_care', models.CharField(max_length=50, verbose_name='Courier Partner Customer Care')),
                ('toll_free_number', models.CharField(max_length=50, verbose_name='Courier Partner Toll Free Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Courier Partner Email')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Addition to cart date')),
                ('shipping_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='shipping_address')),
                ('billing_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='billing_address')),
                ('orderNote', models.CharField(blank=True, max_length=250, null=True, verbose_name='Order Note')),
                ('status', models.CharField(blank=True, choices=[('Shipped', 'SHIPPED'), ('Ordered', 'ORDERED'), ('In-transit', 'IN TRANSIT'), ('Out-For-Delivery', 'OUT FOR DELIVERY'), ('Delivered', 'DELIVERED'), ('Refund Requested', 'REFUND REQUESTED'), ('Refunded', 'REFUNDED')], default='ordered', max_length=255, null=True, verbose_name='Order Status')),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('shipped', models.BooleanField(default=False)),
                ('shipped_date', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateTimeField(auto_now_add=True)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('out_for_delivery_date', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_requested_date', models.DateTimeField(auto_now_add=True)),
                ('refund_granted', models.BooleanField(default=False)),
                ('refund_granted_date', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupon')),
                ('items', models.ManyToManyField(to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Order ID')),
                ('order_payment_id', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Payment ID')),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Buyer Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Buyer Email')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Buyer Name')),
                ('amount', models.FloatField()),
                ('purpose', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Buyer Payment Purpose')),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Payment Status')),
                ('api_response', models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='Payment API Response')),
                ('created_at', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Payment Created At')),
                ('modified_at', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Payment Modified At')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instamojo_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.deliverypartnerdetails', verbose_name='Delivery Partner'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
