# Generated by Django 3.2.5 on 2023-09-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortransactiondetail',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vendordetail', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='vendororderdetail',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='vendororderdetail',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vendordetail', verbose_name='Vendor'),
        ),
    ]
