# Generated by Django 4.1.3 on 2023-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNote',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Order Note'),
        ),
    ]
