# Generated by Django 4.0.4 on 2023-09-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_vendorbankaccountdetail'),
        ('cart', '0004_vendortransactiondetail_vendororderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororderdetail',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Order Item'),
        ),
    ]
