# Generated by Django 4.0.4 on 2023-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_vendororderdetail_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortransactiondetail',
            name='order_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Order Completed on'),
        ),
        migrations.AlterField(
            model_name='vendortransactiondetail',
            name='order_receiving_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Order Received on'),
        ),
    ]
