# Generated by Django 4.0.4 on 2023-09-05 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_alter_vendortransactiondetail_order_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='order_sid',
            field=models.CharField(default='', max_length=50, verbose_name='Order Reference Id'),
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=100, verbose_name='Bank Account No.')),
                ('ifsc_code', models.CharField(max_length=50, verbose_name='IFSC Code')),
                ('account_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Account Holder Name')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nick Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserBankAccount',
                'verbose_name_plural': 'UserBankAccounts',
            },
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.userbankaccount', verbose_name='Refund Bank Account'),
            preserve_default=False,
        ),
    ]
