# Generated by Django 4.1.3 on 2023-04-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_for_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
