# Generated by Django 4.1.3 on 2023-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_out_for_delivery_order_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Courier Partner Name')),
                ('address', models.CharField(max_length=2000, verbose_name='Courier Partner Address')),
                ('contact_no', models.CharField(max_length=50, verbose_name='Courier Partner Contact No')),
                ('customer_care', models.CharField(max_length=50, verbose_name='Courier Partner Customer Care')),
                ('toll_free_number', models.CharField(max_length=50, verbose_name='Courier Partner Toll Free Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Courier Partner Email')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
