# Generated by Django 4.0.4 on 2023-09-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_refund_refund_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_request_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
