# Generated by Django 4.1.3 on 2023-04-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_deliverypartnerdetails_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.deliverypartnerdetails', verbose_name='Delivery Partner'),
        ),
    ]
