# Generated by Django 4.1.3 on 2023-04-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('shipped', 'SHIPPED'), ('ordered', 'ORDERED'), ('in-transit', 'IN TRANSIT'), ('out-for-delivery', 'OUT FOR DELIVERY'), ('delivered', 'DELIVERED'), ('refund-requested', 'REFUND REQUESTED'), ('refunded', 'REFUNDED')], default='ordered', max_length=255, null=True, verbose_name='Order Status'),
        ),
    ]
