# Generated by Django 4.0.4 on 2023-08-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_created_at_cart_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Shipped', 'SHIPPED'), ('Ordered', 'ORDERED'), ('In-transit', 'IN TRANSIT'), ('Out-For-Delivery', 'OUT FOR DELIVERY'), ('Delivered', 'DELIVERED'), ('Refund Requested', 'REFUND REQUESTED'), ('Refunded', 'REFUNDED')], default='ordered', max_length=255, null=True, verbose_name='Order Status'),
        ),
    ]
