# Generated by Django 4.1.3 on 2023-02-04 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='User Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='User Modified Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timeline_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/timelineImages/%Y/%m/%d', verbose_name='Avatar'),
        ),
    ]
