# Generated by Django 4.1.3 on 2023-02-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_created_at_customuser_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='timeline_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/timelineImages/%Y/%m/%d', verbose_name='Cover Photo'),
        ),
    ]
