# Generated by Django 4.1.3 on 2023-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_timeline_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='timeline_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/profile/timelineImages/%Y/%m/%d', verbose_name='Cover Photo'),
        ),
    ]
