# Generated by Django 4.1.3 on 2023-02-04 10:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_timeline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contact Name'),
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='tags',
            field=user.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Address Tags'), null=True, size=None),
        ),
    ]
