# Generated by Django 4.1.3 on 2023-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_useraddresses_name_useraddresses_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/20230220', verbose_name='Avatar'),
        ),
    ]
