# Generated by Django 4.1.3 on 2023-02-24 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/20230224', verbose_name='Avatar'),
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Card Number')),
                ('card_holder_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Card Holder Name')),
                ('exp_month', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Expiry Month')),
                ('exp_year', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Expiry Year')),
                ('set_as_default', models.BooleanField(verbose_name='Set as default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Saved Cards')),
            ],
            options={
                'ordering': ('exp_month', 'exp_year'),
            },
        ),
        migrations.AddConstraint(
            model_name='cards',
            constraint=models.UniqueConstraint(condition=models.Q(('set_as_default', True)), fields=('user',), name='unique_primary_per_customer'),
        ),
    ]
