# Generated by Django 4.1.3 on 2023-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_avatar_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='set_defailt',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Default Address'),
        ),
    ]
