# Generated by Django 4.1.3 on 2023-02-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_useraddresses_set_defailt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='set_defailt',
            new_name='set_default',
        ),
    ]
