# Generated by Django 4.1.3 on 2023-02-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_set_defailt_useraddresses_set_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='addressLine1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='useraddresses',
            name='addressLine2',
        ),
    ]
