# Generated by Django 4.1.3 on 2023-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_addressline1_useraddresses_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='select country'),
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Contact email'),
        ),
    ]
