# Generated by Django 4.1.3 on 2023-02-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_useraddresses_country_useraddresses_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cards',
            name='unique_primary_per_customer',
        ),
        migrations.AddConstraint(
            model_name='cards',
            constraint=models.UniqueConstraint(condition=models.Q(('set_as_default', True)), fields=('user',), name='unique_primary_card_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='useraddresses',
            constraint=models.UniqueConstraint(condition=models.Q(('set_default', True)), fields=('user',), name='unique_primary_address_per_customer'),
        ),
    ]
