# Generated by Django 4.1.3 on 2023-02-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_cards_unique_primary_per_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddresses',
            name='tags',
        ),
    ]
