# Generated by Django 4.1.3 on 2023-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_useraddresses_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='address_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/20230225', verbose_name='Avatar'),
        ),
    ]
