# Generated by Django 4.1.3 on 2023-03-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="user/20230326", verbose_name="Avatar"
            ),
        ),
    ]
