# Generated by Django 4.0.4 on 2023-09-03 09:27

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesdetails',
            name='payment_type',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policiesdetails',
            name='refund_policy',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policiesdetails',
            name='return_policy',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policiesdetails',
            name='shipping_and_delivery_policy',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
