# Generated by Django 4.0.4 on 2023-09-18 04:57

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policiesdetails',
            name='privacy_policy',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
