# Generated by Django 4.0.4 on 2023-09-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_policiesdetails_privacy_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policiesdetails',
            options={'verbose_name': 'Policies', 'verbose_name_plural': 'Policies'},
        ),
    ]
