# Generated by Django 4.0.4 on 2023-08-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorDetail',
        ),
    ]
