# Generated by Django 4.1.3 on 2023-02-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_storedetail_storeservicablepincodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='display_home',
        ),
        migrations.RemoveField(
            model_name='storeproductsdetails',
            name='status',
        ),
    ]
