# Generated by Django 4.0.4 on 2023-08-17 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Store Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Store Email ID')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Store Phone No.')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Store Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'VendorDetail',
                'verbose_name_plural': 'VendorDetails',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vendor', to='products.vendordetail'),
        ),
    ]
