# Generated by Django 4.0.4 on 2023-08-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_vendordetail_alter_products_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('t-shirt-men', 'Tshirt Men'), ('t-shirt-women', 'Tshirt Women'), ('trouser', 'Trouser'), ('night-wear-men', 'Night Wear Men'), ('night-wear-women', 'Night Wear Women'), ('belts-gents', 'Belts Men'), ('belts-women', 'Belts Women'), ('kurta', 'Kurta'), ('kurti', 'Kurti'), ('format-shirt-men', 'Formatshirt Men'), ('format-shirt-women', 'Formatshirt Women'), ('formal-pants-men', 'Formal Pants Men'), ('formal-pants-women', 'Formal Pants Women'), ('wrist-watches', 'Wrist Watches'), ('shoes-men', 'Shoes Men'), ('shoes-women', 'Shoes Women'), ('sandels-men', 'Sandels Men'), ('sandels-women', 'Sandels Women'), ('beauty-products', 'Beauty Products')], max_length=50, null=True, verbose_name='Product Sub-Category'),
        ),
    ]
