# Generated by Django 4.0.4 on 2023-08-29 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_banners_banner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='banners/media/images/%Y/%m/%d', verbose_name='Banner Image'),
            preserve_default=False,
        ),
    ]
