# Generated by Django 4.0.4 on 2023-09-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_banners_banner_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBankAccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(max_length=50, verbose_name='Account No.')),
                ('confirm_bank_account_number', models.CharField(max_length=50, verbose_name='Confirm Account No.')),
                ('ifsc_code', models.CharField(max_length=50, verbose_name='IFSC Code')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vendordetail', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'VendorBankAccountDetail',
                'verbose_name_plural': 'VendorBankAccountDetails',
            },
        ),
    ]
