# Generated by Django 4.1.3 on 2023-01-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_banners_banner_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='CAtegories/media/photos/%Y/%m/%d', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='Products/media/photos/%Y/%m/%d', verbose_name='Product_Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='Products/media/reviews/%Y/%m/%d', verbose_name='ImagesForReview'),
        ),
    ]
