# Generated by Django 4.1.3 on 2023-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_categories_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_images',
            field=models.ImageField(upload_to='Banners/media/images/%Y/%m/%d', verbose_name='bannerimages'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='Categories/media/photos/%Y/%m/%d', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_mainimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Products/media/mainImage/%Y/%m/%d', verbose_name='Product Main Image'),
        ),
    ]
