# Generated by Django 4.0.4 on 2023-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_vendorbankaccountdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbankaccountdetail',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPI Id'),
        ),
    ]
