# Generated by Django 4.1.3 on 2023-01-29 14:37

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_banners_banner_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AlterModelOptions(
            name='productreviewandratings',
            options={'verbose_name_plural': 'ProductReviewAndRatings'},
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name=''),
        ),
        migrations.AddField(
            model_name='productreviewandratings',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_images',
            field=models.ImageField(upload_to='banners/media/images/%Y/%m/%d', verbose_name='bannerimages'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category/media/photos/%Y/%m/%d', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='product/media/photos/%Y/%m/%d', verbose_name='Product_Image'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='upload_image',
            field=models.ImageField(null=True, upload_to='product/media/reviews/%Y/%m/%d', verbose_name='ImagesForReview'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_category',
            field=products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Deal of the day', 'Deal of the day'), ('Best Products', 'Best Products'), ('Trend Products', 'Trend Products'), ('Featured Products', 'Featured Products'), ('Snacks & Drinks', 'Snacks & Drinks'), ('Puja Store', 'Puja Store'), ('Dry Fruits', 'Dry Fruits'), ('Trending', 'TRENDING'), ('Home & Kitchen Appliances', 'Home & Kitchen Appliances'), ('Cleaning Essentials', 'Cleaning Essentials'), ('Personal Care', 'Personal Care'), ('Cooking Essentials', 'Cooking Essentials'), ('Health & Baby Care', 'Health & Baby Care')], max_length=255, null=True, verbose_name='Product Category'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_mainimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/media/mainImage/%Y/%m/%d', verbose_name='Product Main Image'),
        ),
        migrations.AlterModelTable(
            name='productimages',
            table='ProductImages',
        ),
        migrations.AlterModelTable(
            name='productreviewandratings',
            table='ProductReviewAndRatings',
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
