# Generated by Django 4.0.4 on 2023-09-04 07:37

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_vendorbankaccountdetail_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available_sizes',
            field=products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=255, null=True, verbose_name='Product Available'), null=True, size=None),
        ),
    ]
