# Generated by Django 4.1.3 on 2023-01-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_products_pro_category_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prod_mainimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
