# Generated by Django 4.1.3 on 2023-01-29 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_product_id_products_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
    ]
