# Generated by Django 4.1.3 on 2023-01-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_created_at_alter_products_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='products',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prodImages', to='products.products'),
        ),
    ]
