# Generated by Django 4.1.3 on 2023-02-02 07:44

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_image_id_productimages_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewandratings',
            name='prodreviews',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount (in %)'),
        ),
        migrations.AddField(
            model_name='products',
            name='display_home',
            field=models.BooleanField(default=False, verbose_name='Display at home'),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='available stock (in Nos.)'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Organic', 'Organic')], max_length=50, null=True, verbose_name='Tags'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='product rating'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='ratings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Product Rating'),
        ),
    ]
