# Generated by Django 4.1.3 on 2023-02-20 07:06

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_longname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='position',
            field=products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('Home', 'HOME'), ('Categories', 'CATEGORIES'), ('Product Page', 'Product Page'), ('Top', 'TOP'), ('Middle', 'MIDDLE'), ('Bottom', 'BOTTOM')], max_length=255, null=True, verbose_name='Banner Position'), blank=True, null=True, size=None),
        ),
    ]
