# Generated by Django 4.1.3 on 2023-02-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_banners_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_images',
            field=models.ImageField(upload_to='banners/media/images/%Y/%m/%d', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banner Name'),
        ),
    ]
