# Generated by Django 4.1.3 on 2023-03-25 11:08

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_banners_banner_desc_alter_banners_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banners",
            name="position",
            field=products.models.ModifiedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("homepage", "HOME PAGE"),
                        ("categoriespage", "CATEGORIES PAGE"),
                        ("productpage", "PRODUCT PAGE"),
                        ("top", "TOP"),
                        ("middle", "MIDDLE"),
                        ("bottom", "BOTTOM"),
                        ("right", "RIGHT"),
                        ("left", "LEFT"),
                        ("newarrival", "NEW ARRIVAL"),
                        ("men", "MEN"),
                        ("kids", "KIDS"),
                        ("women", "WOMEN"),
                        ("cosmetics", "COSMETICS"),
                        ("browse-more", "Browse More"),
                    ],
                    max_length=255,
                    null=True,
                    verbose_name="Banner Position",
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
