# Generated by Django 4.1.3 on 2023-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_banners_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="banners",
            name="products_available",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Products Available"
            ),
        ),
    ]
