# Generated by Django 4.1.3 on 2023-03-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_banners_products_available"),
    ]

    operations = [
        migrations.RemoveField(model_name="productimages", name="product",),
        migrations.AddField(
            model_name="productimages",
            name="image_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/media/photos/%Y/%m/%d/thumbnails",
                verbose_name="Product Image Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="productimages",
            name="image_thumbnail_color",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Product Thumbnail Color",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="more_images",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productimages",
                verbose_name="Product More Images",
            ),
        ),
    ]
