# Generated by Django 4.1.3 on 2023-03-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_remove_productimages_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="new_arrival",
            field=models.BooleanField(default=False, verbose_name="New"),
        ),
    ]
