# Generated by Django 4.1.3 on 2023-03-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_alter_products_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="products", name="more_images",),
        migrations.AddField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prodImages",
                to="products.products",
            ),
        ),
    ]
