# Generated by Django 4.1.3 on 2023-03-27 05:46

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0026_remove_products_more_images_productimages_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=products.models.ModifiedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("new-arrival", "New Arrival"),
                        ("best-seller", "Best Seller"),
                        ("trending", "Trend Products"),
                        ("Featured Products", "Featured Products"),
                        ("kids-collection", "Kids Collection"),
                    ],
                    max_length=255,
                    null=True,
                    verbose_name="Product Category",
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="tags",
            field=products.models.ModifiedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("cotton", "Cotton"),
                        ("synthetic", "Synthetic"),
                        ("woolen", "Woolen"),
                        ("polyster", "Polyster"),
                    ],
                    max_length=50,
                    null=True,
                    verbose_name="Tags",
                ),
                null=True,
                size=None,
            ),
        ),
    ]
