# Generated by Django 4.1.3 on 2023-04-03 06:11

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_products_category_alter_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=products.models.ModifiedArrayField(base_field=models.CharField(blank=True, choices=[('new-arrival', 'New Arrival'), ('best-seller', 'Best Seller'), ('trending', 'Trend Products'), ('Featured Products', 'Featured Products'), ('kids-collection', 'Kids Collection'), ('hot-collection', 'Hot Collection')], max_length=255, null=True, verbose_name='Product Category'), null=True, size=None),
        ),
    ]
