# Generated by Django 4.1.3 on 2023-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/media/mainImage/%Y/%m/%d', verbose_name='Product Main Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/media/mainImage/%Y/%m/%d', verbose_name='Product Main Image'),
        ),
    ]
