# Generated by Django 4.1.3 on 2023-04-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_products_image1_alter_products_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, default='L', max_length=50, null=True, verbose_name='Item Size'),
        ),
    ]
