# Generated by Django 4.1.3 on 2023-04-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_products_available_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
