# Generated by Django 4.0.4 on 2023-08-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_productreviewandratings_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviewandratings',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
