# Generated by Django 4.0.4 on 2023-08-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_productreviewandratings_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewandratings',
            name='upload_image',
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='ratings',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Product Rating'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='review',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Product Review'),
        ),
    ]
