# Generated by Django 4.0.4 on 2023-08-10 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_productreviewandratings_upload_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewandratings',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 10, 5, 41, 276535), verbose_name='review_date'),
        ),
    ]
