# Generated by Django 4.0.4 on 2023-08-10 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_productreviewandratings_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewandratings',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='product rating'),
        ),
        migrations.AlterField(
            model_name='productreviewandratings',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 10, 12, 12, 720340), verbose_name='review_date'),
        ),
    ]
