# Generated by Django 4.0.4 on 2023-08-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_productreviewandratings_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewandratings',
            name='review_date',
            field=models.DateTimeField(auto_now=True, verbose_name='review_date'),
        ),
    ]
